### ISSUE TITLE
Commenti alle immagini

### ISSUE THREAD

**Issue by Beatrice-nava** [LeggoManzoni/leggomanzoni#1]
Ciao, questione da discutere:

In alcuni dei commenti vengono commentate anche le vignette della quarantana. Come vogliamo/possiamo getsire la cosa?

- caricare anche le immagini (a parte? nel testo?) e rimandare dal commento all'immagine commentata
- eliminare le note di commento all'immagine
- lasciare le note di commento e linkarle al comma in cui l'immagine si inserisce (ma la nota potrebbe esser eun pochino incomprensibile tipo "il ponte sulla destra rappresenta...." senza vedere alcun ponte) 
- altre idee?

**Comment by GiuliaMenna** [comment]
Buongiorno! Mi era sfuggita la domanda, scusami Beatrice. Potremmo forse commentarle comunque nella marcatura con un id prettamente dedicato alle immagini, così che magari qualora le immagini vengano inserite in maniera puntuale nel testo potrebbe comparire in hover con il mouse un piccolo pop-up con la didascalia. Un id potrebbe essere id="image_description".
